# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da213c33042d33851d749cd7300ff7fa022a4aa37b6c12bb0ce58102450a1c0941f67ce58959788b58438c7f02b599ab637b8dca2dc41dc172e0f10f5361c47f
  yandex_key: dict.1.1.20150811T102155Z.2432f34285ac377c.bd39093ee701bc42bd251edfc6c82b013f34d1bf
test:
  secret_key_base: 448837b741120cc57e9ec183d9962372c6495cbb933b1390b2ae9a74613c9743041c29db06f7f172f008b33b363be346d50a8f1b7bf7233c65be1789a7435229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
